import { Link } from "react-router-dom";
import { useMemo } from "react";
import {
  ArrowUpRight,
  BarChart3,
  Download,
  FileText,
  Gauge,
  Printer,
  Scale,
  ShieldCheck,
} from "lucide-react";
import {
  OmegaPage,
  OmegaSection,
  OmegaEmptyState,
} from "@/components/omega/OmegaPage";
import { KpiCard } from "@/components/omega/KpiCard";
import { ProgressBar } from "@/components/omega/ProgressBar";
import { FrameworkPill } from "@/components/omega/FrameworkPill";
import {
  useFrameworkSummaries,
  useOmegaTotals,
} from "@/frameworks/useFrameworkSummaries";
import { Button } from "@/components/ui/button";

function toast(msg: string) {
  if (typeof window === "undefined") return;
  // eslint-disable-next-line no-alert
  window.alert(msg);
}

export default function OmegaReport() {
  const totals = useOmegaTotals();
  const entries = useFrameworkSummaries();

  const active = useMemo(
    () => entries.filter((e) => e.summary),
    [entries],
  );

  const handlePrint = () => {
    if (typeof window !== "undefined") window.print();
  };

  return (
    <OmegaPage
      eyebrow="Omega · Reporting"
      title="Reports"
      description="Executive and framework-level compliance posture reports ready for audit, board and team reviews."
      icon={<FileText className="h-5 w-5" />}
      actions={
        <>
          <Button variant="outline" size="sm" onClick={handlePrint}>
            <Printer className="mr-1.5 h-3.5 w-3.5" /> Print
          </Button>
          <Button
            size="sm"
            onClick={() => toast("PDF export will be generated by the server in a future release.")}
          >
            <Download className="mr-1.5 h-3.5 w-3.5" /> Export PDF
          </Button>
        </>
      }
    >
      {/* Executive summary */}
      <OmegaSection
        title="Executive report"
        description="Board-level snapshot of your cross-framework compliance posture."
      >
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
          <KpiCard
            label="Overall readiness"
            value={totals.averageReadiness === null ? "—" : `${totals.averageReadiness}%`}
            tone={
              (totals.averageReadiness ?? 0) >= 70
                ? "success"
                : (totals.averageReadiness ?? 0) >= 40
                  ? "warning"
                  : "danger"
            }
            icon={ShieldCheck}
          />
          <KpiCard
            label="Controls assessed"
            value={`${totals.assessedControls}/${totals.totalControls}`}
            icon={Gauge}
            tone="info"
          />
          <KpiCard
            label="Open gaps"
            value={totals.openGaps}
            tone={totals.openGaps > 0 ? "warning" : "default"}
          />
          <KpiCard
            label="Critical risks"
            value={totals.criticalRisks}
            tone={totals.criticalRisks > 0 ? "danger" : "success"}
          />
        </div>
      </OmegaSection>

      {/* Comparison report */}
      <OmegaSection
        title="Framework comparison"
        description="Side-by-side compliance posture."
      >
        {active.length === 0 ? (
          <OmegaEmptyState
            title="No active framework data"
            description="Start an assessment in any framework to produce comparison reports."
            icon={<BarChart3 className="h-5 w-5" />}
          />
        ) : (
          <div className="overflow-hidden rounded-xl border border-border/60 bg-card shadow-sm">
            <table className="w-full text-sm">
              <thead className="bg-muted/40 text-xs uppercase tracking-wider text-muted-foreground">
                <tr>
                  <th className="px-4 py-2 text-left font-semibold">Framework</th>
                  <th className="px-4 py-2 text-left font-semibold">Progress</th>
                  <th className="px-4 py-2 text-left font-semibold">Readiness</th>
                  <th className="px-4 py-2 text-left font-semibold">Avg. maturity</th>
                  <th className="px-4 py-2 text-left font-semibold">Open gaps</th>
                  <th className="px-4 py-2 text-left font-semibold">Critical risks</th>
                  <th className="px-4 py-2 text-left font-semibold">Evidence</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border/60">
                {active.map(({ framework, summary }) => (
                  <tr key={framework.id} className="hover:bg-muted/30">
                    <td className="px-4 py-2.5">
                      <Link
                        to={framework.basePath}
                        className="flex items-center gap-2 font-medium text-foreground hover:underline"
                      >
                        <FrameworkPill framework={framework} />
                        {framework.name}
                      </Link>
                    </td>
                    <td className="px-4 py-2.5">
                      <div className="flex items-center gap-2">
                        <ProgressBar
                          value={summary!.assessmentProgress ?? 0}
                          tone="info"
                          className="w-24"
                        />
                        <span className="text-xs tabular-nums text-foreground">
                          {summary!.assessmentProgress ?? 0}%
                        </span>
                      </div>
                    </td>
                    <td className="px-4 py-2.5">
                      <div className="flex items-center gap-2">
                        <ProgressBar
                          value={summary!.readinessScore ?? 0}
                          tone={
                            (summary!.readinessScore ?? 0) >= 70
                              ? "success"
                              : (summary!.readinessScore ?? 0) >= 40
                                ? "warning"
                                : "danger"
                          }
                          className="w-24"
                        />
                        <span className="text-xs tabular-nums text-foreground">
                          {summary!.readinessScore ?? 0}%
                        </span>
                      </div>
                    </td>
                    <td className="px-4 py-2.5 tabular-nums">
                      {summary!.averageMaturity
                        ? summary!.averageMaturity.toFixed(1)
                        : "—"}
                    </td>
                    <td className="px-4 py-2.5 tabular-nums">
                      {summary!.openGaps}
                    </td>
                    <td className="px-4 py-2.5 tabular-nums">
                      {summary!.criticalRisks}
                    </td>
                    <td className="px-4 py-2.5 tabular-nums">
                      {summary!.evidenceCount}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </OmegaSection>

      {/* Framework-specific reports */}
      <OmegaSection
        title="Framework-specific reports"
        description="Download or view each framework's dedicated reporting workspace."
      >
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
          {active.map(({ framework, summary }) => (
            <Link
              key={framework.id}
              to={`${framework.basePath}/report`}
              className="group flex items-start gap-3 rounded-xl border border-border/60 bg-card p-4 shadow-sm transition-all hover:border-primary/40 hover:shadow-md"
            >
              <div className="flex h-10 w-10 flex-none items-center justify-center rounded-md bg-primary/10 text-primary">
                <FileText className="h-4 w-4" />
              </div>
              <div className="min-w-0 flex-1">
                <div className="flex items-center justify-between">
                  <div className="text-sm font-semibold text-foreground">
                    {framework.name}
                  </div>
                  <ArrowUpRight className="h-3.5 w-3.5 text-muted-foreground transition-transform group-hover:translate-x-0.5" />
                </div>
                <div className="mt-0.5 text-xs text-muted-foreground">
                  Readiness{" "}
                  <span className="font-semibold text-foreground">
                    {summary!.readinessScore ?? 0}%
                  </span>{" "}
                  · {summary!.assessedControls}/{summary!.totalControls} controls
                </div>
              </div>
            </Link>
          ))}
        </div>
      </OmegaSection>

      {/* Additional report types */}
      <OmegaSection title="Available report templates">
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
          <ReportCard
            icon={ShieldCheck}
            title="Audit readiness report"
            description="Readiness score, blockers, approved controls and pending reviews by framework."
            href="/audit-readiness"
          />
          <ReportCard
            icon={Scale}
            title="Cross-framework coverage"
            description="Which controls are satisfied across frameworks, via the Omega crosswalk."
            href="/cross-mapping"
          />
          <ReportCard
            icon={BarChart3}
            title="Compliance posture summary"
            description="Executive-ready summary of compliance posture across all frameworks."
            href="#"
            onClick={() =>
              toast(
                "Compliance posture summary export will be available in a future release.",
              )
            }
          />
        </div>
      </OmegaSection>
    </OmegaPage>
  );
}

function ReportCard({
  icon: Icon,
  title,
  description,
  href,
  onClick,
}: {
  icon: typeof FileText;
  title: string;
  description: string;
  href: string;
  onClick?: () => void;
}) {
  const content = (
    <div className="group flex h-full items-start gap-3 rounded-xl border border-border/60 bg-card p-4 shadow-sm transition-all hover:border-primary/40 hover:shadow-md">
      <div className="flex h-10 w-10 flex-none items-center justify-center rounded-md bg-primary/10 text-primary">
        <Icon className="h-4 w-4" />
      </div>
      <div className="min-w-0 flex-1">
        <div className="flex items-center justify-between">
          <div className="text-sm font-semibold text-foreground">{title}</div>
          <ArrowUpRight className="h-3.5 w-3.5 text-muted-foreground transition-transform group-hover:translate-x-0.5" />
        </div>
        <p className="mt-0.5 text-xs text-muted-foreground">{description}</p>
      </div>
    </div>
  );
  if (onClick) {
    return (
      <button onClick={onClick} className="text-left">
        {content}
      </button>
    );
  }
  return <Link to={href}>{content}</Link>;
}
