/**
 * ISO 27001:2022 — workspace data types.
 *
 * This file is the single source of truth for how the ISO 27001
 * workspace shapes its clauses, Annex A controls, question bank,
 * evidence model, risk register, SoA and remediation flow.
 */

export type AnswerType =
  | "yes-no"
  | "implementation-status"
  | "maturity"
  | "single-select"
  | "multi-select"
  | "text"
  | "date"
  | "numeric"
  | "evidence";

export type ImplementationStatus =
  | "not-implemented"
  | "planned"
  | "partial"
  | "implemented"
  | "not-applicable";

export type Applicability = "applicable" | "not-applicable" | "under-review";

export type QuestionDepth =
  | "existence"
  | "documentation"
  | "implementation"
  | "effectiveness"
  | "review";

export type QuestionCategory =
  | "governance"
  | "policy"
  | "implementation"
  | "monitoring"
  | "evidence"
  | "exception"
  | "review";

export type AnnexDomain = "A.5" | "A.6" | "A.7" | "A.8";

export interface EvidenceExample {
  id: string;
  label: string;
  type?: string;
}

export interface AssessmentQuestion {
  /** Stable id, unique across the whole question bank. */
  id: string;
  /** Reference (e.g. "6.1.2" or "A.5.15"). */
  reference: string;
  title: string;
  text: string;
  guidance?: string;
  whyItMatters?: string;
  answerType: AnswerType;
  options?: string[];
  /** Weight applied to this question when computing readiness score. */
  weight?: number;
  depth: QuestionDepth;
  category?: QuestionCategory;
  /** Suggested evidence artefacts (shown as checklist). */
  evidence: EvidenceExample[];
  /** When true, evidence attachment is required before the question can close. */
  evidenceRequired?: boolean;
  reviewerApprovalRequired?: boolean;
  /** Organisation-profile keys that must be true for this question to appear. */
  appliesWhen?: string[];
  /** Keys that, when any is true, will hide this question (e.g. physical when no-office). */
  hideWhen?: string[];
  /** Follow-up behaviour. */
  followUp?: {
    /** Show these question ids if the answer matches one of the triggers. */
    whenAnswerIn?: string[];
    revealQuestionIds?: string[];
    requireJustificationWhenAnswerIn?: string[];
  };
  /** Maturity ceiling without review evidence. */
  maturityCeilingWithoutReview?: number;
}

export interface ClauseSection {
  id: string;
  number: string;
  name: string;
  summary: string;
  objectives: string[];
  questions: AssessmentQuestion[];
}

export interface AnnexControl {
  id: string;
  reference: string;
  name: string;
  domain: AnnexDomain;
  domainName: string;
  objective: string;
  guidance: string;
  purpose?: string;
  failureIndicators: string[];
  linkedRiskAreas?: string[];
  appliesWhen?: string[];
  hideWhen?: string[];
  defaultApplicability: Applicability;
  /** Specific, tailored questions (generated by combining templates with control context). */
  questions: AssessmentQuestion[];
}

export interface AnnexDomainGroup {
  domain: AnnexDomain;
  name: string;
  description: string;
  controls: AnnexControl[];
}

/**
 * Organisation profile flags drive conditional question logic.
 * Values are intentionally yes/no so the logic engine is simple.
 */
export interface OrganisationProfile {
  usesCloud: boolean;
  developsSoftware: boolean;
  remoteWorkers: boolean;
  thirdPartyProcessors: boolean;
  handlesPii: boolean;
  multipleLocations: boolean;
  hasPhysicalOffice: boolean;
  handlesPayments: boolean;
  /** When true, controls relying on outsourced operations expand. */
  outsourcedOperations: boolean;
  /** Organisation name — shown throughout the workspace. */
  organisationName?: string;
  /** Defined ISMS scope. */
  ismsScope?: string;
  /** Industry sector — used on the overview. */
  sector?: string;
}

export const DEFAULT_ORG_PROFILE: OrganisationProfile = {
  usesCloud: true,
  developsSoftware: false,
  remoteWorkers: true,
  thirdPartyProcessors: true,
  handlesPii: true,
  multipleLocations: false,
  hasPhysicalOffice: true,
  handlesPayments: false,
  outsourcedOperations: false,
  organisationName: "",
  ismsScope: "",
  sector: "",
};

export const ANSWER_OPTIONS: Record<string, string[]> = {
  "implementation-status": [
    "Implemented",
    "Partially implemented",
    "Planned",
    "Not implemented",
    "Not applicable",
  ],
  "yes-no": ["Yes", "No", "Not applicable"],
};

export const MATURITY_LABELS: Record<number, string> = {
  0: "0 — Non-existent",
  1: "1 — Initial / ad-hoc",
  2: "2 — Repeatable but informal",
  3: "3 — Defined and documented",
  4: "4 — Managed and measured",
  5: "5 — Optimising",
};
